# Generated by Django 6.0 on 2026-01-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_wishlist_unique_together_wishlist_size_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image_url',
            field=models.URLField(blank=True, help_text='Enter image URL if not uploading a file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Enter image URL if not uploading a file', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='catgories'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
